trin_base_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'left_wheel'
  right_wheel : 'right_wheel'
  publish_rate: 100.0
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  wheel_separation : 0.1778
  wheel_radius : 0.04

  wheel_separation_multiplier: 1.0
  wheel_radius_multiplier    : 1.0

  cmd_vel_timeout: 0.25
  base_frame_id: base_link

  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.12
      min_velocity           : -1.12
      has_acceleration_limits: true
      max_acceleration       : 3.0
      min_acceleration       : -3.0
      has_jerk_limits        : true
      max_jerk               : 10.0
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 5
      has_acceleration_limits: true
      max_acceleration       : 30
      has_jerk_limits        : true
      max_jerk               : 10.5

enable_odom_tf: true
odom_frame_id: odom
publish_cmd: false
